module.exports = {
    //MONTHLY: 'MONTHLY',
    //WEEKLY: 'WEEKLY',
    //DAILY: 'DAILY',
    //HOURLY: '60min',
    //MINUTELY: 'MINUTELY',
    // ONE_MIN: '1min',
    // FIVE_MIN: '5min',
    // FIFTEEN_MIN: '15min',
    DATA_KEY_5MIN: 'Time Series (5min)',
    DATA_KEY_1MIN: 'Time Series (1min)',
    DATA_KEY_15MIN: 'Time Series (15min)',
    DATA_KEY_60MIN: 'Time Series (60min)',
    DATA_KEY_DAILY: 'Time Series (Daily)',
    INTRA_DAY: 'TIME_SERIES_INTRADAY',
    DAILY: 'TIME_SERIES_DAILY_ADJUSTED',
    CLOSE_DAILY: '5. adjusted close',
    VOLUME_DAILY: '6. volume',
    CLOSE_INTRADAY: '4. close',
    VOLUME_INTRADAY: '5. volume',
    //INTERVALS: ['hour' ]  //TODO delete unused constants
};